version: '3'

services:
  nginx:
    container_name: tcom_nginx
    image: 'nginx:stable'
    ports:
      -  "8080:80"
    volumes:
      - ./src/tcom:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: tcom_php
    build: 
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/tcom:/var/www/html
    ports:
      - "9000:9000"

  mysql:
    container_name: tcom_mysql
    image: mysql:8.0.29-oracle
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: tcom_db
      MYSQL_USER: tcom_user
      MYSQL_PASSWORD: tcomadmin123
      MYSQL_ROOT_PASSWORD: admin123